/** music-core — moteur musical isomorphe. Manuel §3, Consolidation §3. */
export const ENGINE_VER = '0.1.0';
export * from './types.js';
export * from './analyzers/key.js';
export * from './analyzers/chord.js';
export * from './analyzers/cadence.js';
export * from './analyzers/collection.js';
export * from './analyzers/idioms.js';
export * from './analyzers/motifs.js';
export * from './analyzers/contour.js';
export * from './analyzers/phrase.js';
export * from './analyzers/rhythm.js';
export * from './analyzers/tension.js';
export * from './analyzers/swing.js';
export * from './analyzers/chordscale.js';
export * from './analyzers/voiceleading.js';
export * from './analyzers/species.js';
export * from './analyzers/imitation.js';
export * from './analyzers/suspension.js';
export * from './analyzers/orchestration.js';
export * from './data/krumhansl.js';
export * from './data/chordForms.js';
export * from './data/idioms.js';
export * from './data/moods.js';
export * from './data/chordScales.js';
export * from './data/instruments.js';
export * from './data/instruments.js';